# Generated by Django 4.2.7 on 2025-08-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, help_text='e.g. Home, Office, etc.', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this location for the contact')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gate_code', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('property_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_location', to='accounts.contact')),
            ],
        ),
    ]
