# Generated by Django 4.2.7 on 2025-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_alter_globalsizepackage_max_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed quantity', null=True),
        ),
    ]
