# Generated by Django 4.2.7 on 2025-09-08 18:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_alter_questionoption_max_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
