# Generated by Django 4.2.7 on 2025-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_remove_service_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBase_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Global base price applied across the system.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
