# Generated by Django 4.2.7 on 2025-09-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0011_globalbase_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalBase_price',
            new_name='GlobalBasePrice',
        ),
    ]
