# Generated by Django 4.2.7 on 2025-08-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('quote_app', '0005_customersubmission_additional_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubmission',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='ghl_contact_id',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='location',
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
    ]
