# Generated by Django 4.2.7 on 2025-08-19 19:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0007_customservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='custom_service_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
