# Generated by Django 4.2.7 on 2025-08-19 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0008_customersubmission_custom_service_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubmission',
            name='custom_service_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
