# Generated by Django 4.2.7 on 2025-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0009_alter_customersubmission_custom_service_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_time', models.BooleanField(default=True)),
                ('quoted_by', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, help_text='Any internal notes about the booking.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_schedule', to='quote_app.customersubmission')),
            ],
        ),
    ]
