# Generated by Django 4.2.7 on 2025-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0010_quoteschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteschedule',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
