# Generated by Django 4.2.7 on 2025-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0011_alter_quoteschedule_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteschedule',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
