# Generated by Django 4.2.7 on 2025-09-08 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0013_customerpackagequote_service_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpackagequote',
            name='service_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
