# Generated by Django 4.2.7 on 2025-09-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0014_alter_customerpackagequote_service_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpackagequote',
            name='service_base_price',
        ),
    ]
