# Generated by Django 4.2.7 on 2025-09-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0015_remove_customerpackagequote_service_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
