# Generated by Django 4.2.7 on 2025-10-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0016_customservice_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerserviceselection',
            options={'ordering': ['service__order', 'service__name']},
        ),
    ]
