# Generated by Django 4.2.7 on 2025-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0017_alter_customerserviceselection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteschedule',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
